services:
  webapp:
    image: bartinvienna/webapp
    ports:
      - "3000:3000"
    volumes:
    - ./database:/app/database
    environment:
      - NODE_ENV=${NODE_ENV}
      - MYSQL_URL=${MYSQL_URL}
    command: yarn start
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql

  test:
    image: bartinvienna/webapp
    command: yarn test
    environment:
      - NODE_ENV=test
      - MYSQL_URL=${MYSQL_URL}
      - API_URL=http://webapp:3000
    depends_on:
      - webapp
    profiles:
      - test

  
volumes:
  mysql_data: