services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
    - ./database:/app/database
    environment:
      - NODE_ENV=development
    command: yarn start
  
volumes:
  database: