name: build and test
on:
  push:
    branches:
      - main
env:
  ESLINT_USE_FLAT_CONFIG: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: |
          cd webapp 
          yarn install
      
      - name: Run linter
        id: linter
        run: |
          cd webapp
          yarn lint
        continue-on-error: false

      - name: Debug linter if it fails
        if: failure()
        run: |
          cd webapp
          yarn lint --debug

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./webapp
          file: ./webapp/Dockerfile
          push: true
          tags: bartinvienna/webapp:latest
          outputs: type=docker,dest=/tmp/myapp.tar

      - name: Load Docker image
        run: |
          docker load -i /tmp/myapp.tar
          docker image ls
