name: build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: |
          cd webapp 
          yarn install
      
      - name: Run linter
        id: linter
        run: |
          cd webapp
          yarn lint
        continue-on-error: true

      - name: Debug linter if it fails
        if: failure()
        run: |
          cd webapp
          yarn lint --debug
